[ether]
addr = "ws://host.docker.internal:8546"
name = "ether"
contract_address = "0xD3880ea40670eD51C3e3C0ea089fDbDc9e3FBBb4"
key_path = "account.key"
password = "password"
min_confirm = 1

[contract_abi]
0x5ff1B3309A9e71Ac6944CEc887AA66a31dc5A691="data_swapper.abi"
0x30b7DF1b3bEc59Fd1b28B4b311df5bEeEc090af1="transfer.abi"