[ether]
addr = "{{.AppchainAddr}}"
name = "ether"
contract_address = "{{.AppchainContractAddr}}"
key_path = "account.key"
password = "password"
min_confirm = 0

[contract_abi]
0x6db07a8b0f23367dc65c7DAD91da4F6bfD97D674="data_swapper.abi"
0x668a209Dc6562707469374B8235e37b8eC25db08="transfer.abi"