[hosts]
  [[hosts.host]]
    host_lable = host1 # (自定义)主机标签
    ip = 127.0.0.1
    # 主机用户名
    user = xxx
    # 主机ssh密钥文件名(config/cert/host目录下)
    key = host1
  [[hosts.host]]
    host_lable = host2
    ip = 127.0.0.1
    # 主机用户名
    user = ubuntu
    # 主机ssh密钥文件名(config/cert/host目录下)
    key = host2
  [[hosts.host]]
    host_lable = host3
    ip = 127.0.0.1
    # 主机用户名
    user = ubuntu
    # 主机ssh密钥文件名(config/cert/host目录下)
    key = host3
[common]
  # 当前配置文件所在主机(若不属于上述hosts下主机, 可填写other)
  current_host = other
[bitxhub]
  mode = cluster
  num = 4
  consensus_type = raft
  rewrite = true
  # absolute path. It doesn't have to be in double quotes.
  agency_priv_path = REPO/bitxhub/certs/agency.priv
  agency_cert_path = REPO/bitxhub/certs/agency.cert
  ca_cert_path = REPO/bitxhub/certs/ca.cert
  [[bitxhub.node1]]
    node_host = host1
    grpc_port = 60011
    gateway_port = 9091
    pprof_port = 53121
    monitor_port = 40011
  [[bitxhub.node2]]
    node_host = host1
    grpc_port = 60012
    gateway_port = 9092
    pprof_port = 53122
    monitor_port = 40012
  [[bitxhub.node3]]
    node_host = host1
    grpc_port = 60013
    gateway_port = 9093
    pprof_port = 53123
    monitor_port = 40013
  [[bitxhub.node4]]
    node_host = host1
    grpc_port = 60014
    gateway_port = 9094
    pprof_port = 53124
    monitor_port = 40014

